version: "3.8"

services:

  jenkins:
    build:
      context: ./component-3-ci-pipeline
      dockerfile: docker/Dockerfile.jenkins
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
      - .:/workspace

  k6:
    image: grafana/k6
    volumes:
      - ./component-7-load-testing:/scripts
    working_dir: /scripts

  postgres:
    image: postgres:15
    container_name: qa-lab-postgres
    restart: always
    environment:
      POSTGRES_USER: qa_user
      POSTGRES_PASSWORD: qa_pass
      POSTGRES_DB: qa_lab
    ports:
      - "5432:5432"
    volumes:
      - qa_lab_data:/var/lib/postgresql/data
      - ./component-8-data-platform/db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  jenkins_home:
  qa_lab_data: